# This file contains the default values for the Canteen App Helm chart.

# Add your tumid here
tumid: go67yja

##################################################################################################################
# No changes needed below this line
namespace:
  create: false

server:
  image:
    repository: ghcr.io/devops26hn/w05-template/server
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

client:
  image:
    repository: ghcr.io/devops26hn/w05-template/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  replicaCount: 1

ingress:
  enabled: true
  className: "ingress-appgateway-appgwpip"

  hosts:
    - host: your_ip  # You can use your App Gateway's Public IP here
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client-service  # Ensure this matches your client service name
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: server-service  # Ensure this matches your server service name
              port:
                number: 8080
